/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020 https://prrvchr.github.io                                     ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
*/
package io.github.prrvchr.uno.sdbcx;

import java.util.LinkedHashMap;
import java.util.Map;

import com.sun.star.beans.Property;
import com.sun.star.beans.PropertyAttribute;
import com.sun.star.sdbc.ColumnValue;
import com.sun.star.sdbc.DataType;

import io.github.prrvchr.uno.helper.UnoHelper;
import io.github.prrvchr.uno.sdbc.ConnectionBase;


public class Column
    extends ContainerElement
{
    private static final String m_name = Column.class.getName();
    private static final String[] m_services = {"com.sun.star.sdbcx.Column"};
    private int m_Type = DataType.SQLNULL;
    @SuppressWarnings("unused")
	private String m_TypeName = "SQLNULL";
    @SuppressWarnings("unused")
	private int m_Precision = 0;
    @SuppressWarnings("unused")
	private int m_Scale = 0;
    @SuppressWarnings("unused")
	private int m_IsNullable = ColumnValue.NULLABLE;
    @SuppressWarnings("unused")
	private boolean m_IsAutoIncrement = false;
    @SuppressWarnings("unused")
    private boolean m_IsCurrency = false;
    @SuppressWarnings("unused")
    private final boolean m_IsRowVersion = false;
    @SuppressWarnings("unused")
    private String m_Description = "";
    @SuppressWarnings("unused")
    private String m_DefaultValue = "";

    @SuppressWarnings("unused")
    private String m_AutoIncrementCreation = "GENERATED BY DEFAULT AS IDENTITY";
    @SuppressWarnings("unused")
    private String m_CatalogName = "";
    @SuppressWarnings("unused")
    private String m_SchemaName = "";
    @SuppressWarnings("unused")
    private String m_TableName = "";
    private static Map<String, Property> _getPropertySet(boolean readonly)
    {
        short ro = readonly ? PropertyAttribute.READONLY : 0;
        Map<String, Property> map = new LinkedHashMap<String, Property>();
        map.put("m_Type", UnoHelper.getProperty("Type", "long", ro));
        map.put("m_TypeName", UnoHelper.getProperty("TypeName", "string", ro));
        map.put("m_Precision", UnoHelper.getProperty("Precision", "long", ro));
        map.put("m_Scale", UnoHelper.getProperty("Scale", "long", ro));
        map.put("m_IsNullable", UnoHelper.getProperty("IsNullable", "long", ro));
        map.put("m_IsAutoIncrement", UnoHelper.getProperty("IsAutoIncrement", "boolean", ro));
        map.put("m_IsCurrency", UnoHelper.getProperty("IsCurrency", "boolean", ro));
        map.put("m_IsRowVersion", UnoHelper.getProperty("IsRowVersion", "boolean", ro));
        map.put("m_Description", UnoHelper.getProperty("Description", "string", ro));
        map.put("m_DefaultValue", UnoHelper.getProperty("DefaultValue", "string", ro));
        return map;
    }
    private static Map<String, Property> _getPropertySet(Map<String, Property> map, boolean readonly)
    {
        short ro = readonly ? PropertyAttribute.READONLY : 0;
        map.put("m_AutoIncrementCreation", UnoHelper.getProperty("AutoIncrementCreation", "string", ro));
        map.put("m_CatalogName", UnoHelper.getProperty("CatalogName", "string", ro));
        map.put("m_SchemaName", UnoHelper.getProperty("SchemaName", "string", ro));
        map.put("m_TableName", UnoHelper.getProperty("TableName", "string", ro));
        return map;
    }

    // The constructor method:
    public Column(ConnectionBase connection,
                  String catalog,
                  String schema,
                  String table)
    {
        super(m_name, m_services, connection, _getPropertySet(_getPropertySet(false), false));
        m_CatalogName = catalog;
        m_SchemaName = schema;
        m_TableName = table;
    }
    public Column(ConnectionBase connection,
                  java.sql.ResultSet result,
                  String catalog,
                  String schema,
                  String table,
                  String name)
        throws java.sql.SQLException
    {
        super(m_name, m_services, connection, _getPropertySet(_getPropertySet(true), true), name);
        m_Type = UnoHelper.mapSQLDataType(result.getInt(5));
        m_TypeName = UnoHelper.mapSQLDataTypeName(result.getString(6), m_Type);
        m_Precision = result.getInt(9);
        m_Scale = result.getInt(10);
        m_IsNullable = result.getInt(11);
        m_IsAutoIncrement = ("YES".equals(result.getString(23))) ? true : false;
        m_CatalogName = catalog;
        m_SchemaName = schema;
        m_TableName = table;
    }
    public Column(ConnectionBase connection,
                  java.sql.ResultSetMetaData metadata,
                  int index,
                  String name)
    throws java.sql.SQLException
    {
        super(m_name, m_services, connection, _getPropertySet(true), name);
        m_Type = UnoHelper.mapSQLDataType(metadata.getColumnType(index));
        m_TypeName = UnoHelper.mapSQLDataTypeName(metadata.getColumnTypeName(index), m_Type);
        m_Precision = metadata.getPrecision(index);
        m_Scale = metadata.getScale(index);
        m_IsNullable = metadata.isNullable(index);
        m_IsAutoIncrement = metadata.isAutoIncrement(index);
        m_IsCurrency = metadata.isCurrency(index);
    }

    public Column(ConnectionBase connection,
                  schemacrawler.schema.Column column,
                  String catalog,
                  String schema,
                  String table,
                  String name)
    {
        super(m_name, m_services, connection, _getPropertySet(_getPropertySet(true), true), name);
        m_Type = UnoHelper.mapSQLDataType(column.getColumnDataType().getJavaSqlType().getVendorTypeNumber());
        m_TypeName = UnoHelper.mapSQLDataTypeName(column.getColumnDataType().getName(), m_Type);
        m_Precision = (int) column.getColumnDataType().getPrecision();
        m_Scale = column.getColumnDataType().getMaximumScale();
        m_IsNullable = (column.isNullable()) ? ColumnValue.NULLABLE : ColumnValue.NO_NULLS;
        m_IsAutoIncrement = column.isAutoIncremented();
        m_Description = column.getRemarks();
        m_DefaultValue = column.getDefaultValue();
        m_CatalogName = catalog;
        m_SchemaName = schema;
        m_TableName = table;
    }
    public Column(ConnectionBase connection,
                  schemacrawler.schema.ResultsColumn column,
                  String name)
    {
        super(m_name, m_services, connection, _getPropertySet(true), name);
        m_Type = UnoHelper.mapSQLDataType(column.getColumnDataType().getJavaSqlType().getVendorTypeNumber());
        m_TypeName = UnoHelper.mapSQLDataTypeName(column.getColumnDataType().getName(), m_Type);
        m_Precision = (int) column.getColumnDataType().getPrecision();
        m_Scale = column.getColumnDataType().getMaximumScale();
        m_IsNullable = (column.isNullable()) ? ColumnValue.NULLABLE : ColumnValue.NO_NULLS;
        m_IsAutoIncrement = column.isAutoIncrement();
        m_Description = column.getRemarks();
        m_DefaultValue = ((schemacrawler.schema.Column) column).getDefaultValue();
    }


}
