#ifndef __io_github_prrvchr_jdbcdriver_sdbc_Driver_idl__
#define __io_github_prrvchr_jdbcdriver_sdbc_Driver_idl__

#include <com/sun/star/sdbc/Driver.idl>

module io { module github { module prrvchr { module jdbcdriver { module sdbc {

    service Driver {

        service com::sun::star::sdbc::Driver;

    };

}; }; }; }; };

#endif

