#ifndef __com_sun_star_sdbc_XRestDataSource_idl__
#define __com_sun_star_sdbc_XRestDataSource_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/sdbc/XRestProvider.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>
#include <com/sun/star/sdbc/XConnection.idl>
#include <com/sun/star/sdbc/XPreparedStatement.idl>
#include <com/sun/star/beans/Optional.idl>
#include <com/sun/star/logging/XLogger.idl>

module com { module sun { module star { module sdbc {

interface XRestDataSource: com::sun::star::uno::XInterface
{

    any getWarnings();
    void clearWarnings();

    boolean isConnected();
    long getIdentity();

    ::com::sun::star::uno::XInterface getRequest([in] string Name);
    sequence<string> getUserFields();
    ::com::sun::star::uno::XInterface getUser([in] string Name,
                                              [in] string Password);
    ::com::sun::star::auth::XRestKeyMap selectUser([in] string Name);
    ::com::sun::star::auth::XRestKeyMap getFieldsMap([in] string Method,
                                                     [in] boolean Reverse);
    sequence<string> getUpdatedGroups([in] ::com::sun::star::uno::XInterface User,
                                      [in] string Prefix);

    void createGroupView([in] ::com::sun::star::uno::XInterface User,
                         [in] string Name,
                         [in] long Group);
    void dropGroupView([in] ::com::sun::star::uno::XInterface User,
                       [in] string Name);

    void updateSyncToken([in] ::com::sun::star::uno::XInterface User,
                         [in] string Token,
                         [in] string Value,
                         [in] ::com::sun::star::util::DateTime TimeStamp);

    ::com::sun::star::sdbc::XPreparedStatement getDataSourceCall([in] string Name);
    ::com::sun::star::sdbc::XPreparedStatement getPreparedCall([in] string Name);
    void closeDataSourceCall();

    [attribute, readonly] ::com::sun::star::sdbc::XRestProvider Provider;
    [attribute, readonly] ::com::sun::star::uno::XInterface Connection;

};

}; }; }; };

#endif
