#ifndef __io_github_prrvchr_jdbcDriverOOo_sdbcx_driver_idl__
#define __io_github_prrvchr_jdbcDriverOOo_sdbcx_driver_idl__

#include <com/sun/star/sdbc/XDriver.idl>

module io { module github { module prrvchr { module jdbcDriverOOo { module sdbcx {

	service Driver : com::sun::star::sdbc::XDriver {

	};

 }; }; }; }; };
#endif
