#ifndef __io_github_prrvchr_jdbcdriver_logging_DBLoggerPool_idl__
#define __io_github_prrvchr_jdbcdriver_logging_DBLoggerPool_idl__

#include <io/github/prrvchr/jdbcdriver/logging/XDBLoggerPool.idl>

module io { module github { module prrvchr { module jdbcdriver { module logging {

    service DBLoggerPool : io::github::prrvchr::jdbcdriver::logging::XDBLoggerPool {

    };

}; }; }; }; };

#endif

