#ifndef __io_github_prrvchr_jdbcdriverooo_idl__
#define __io_github_prrvchr_jdbcdriverooo_idl__

#include <io/github/prrvchr/XJdbcDriverOOo.idl>
module io { module github { module prrvchr { 	

	service JdbcDriverOOo : io::github::prrvchr::XJdbcDriverOOo {

	};

 }; }; };
#endif
