#ifndef __io_github_prrvchr_jdbcdriver_SdbcxDriver_idl__
#define __io_github_prrvchr_jdbcdriver_SdbcxDriver_idl__

#include <com/sun/star/sdbcx/Driver.idl>

module io { module github { module prrvchr { module jdbcdriver {

    service SdbcxDriver
    {
        service com::sun::star::sdbcx::Driver;
    };

}; }; }; };

#endif

