/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020 https://prrvchr.github.io                                     ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
*/
package io.github.prrvchr.uno.sdbc;

import java.sql.SQLException;
import java.util.Map;

import com.sun.star.beans.Property;
import com.sun.star.beans.PropertyValue;
import com.sun.star.uno.XComponentContext;

import io.github.prrvchr.jdbcdriver.DriverProvider;


public abstract class PreparedStatementBase
    extends PreparedStatementMain
{

    protected java.sql.Connection m_Connection;
    private java.sql.PreparedStatement m_Statement = null;
    private String m_Sql;

    // The constructor method:
    public PreparedStatementBase(XComponentContext context,
                                 String name,
                                 String[] services,
                                 DriverProvider provider,
                                 ConnectionBase xConnection,
                                 java.sql.Connection connection,
                                 String sql,
                                 PropertyValue[] info)
    {
        super(context, name, services, provider, xConnection, info);
        m_Connection = connection;
        m_Sql = sql;
        System.out.println("sdbc.BasePreparedStatement() 1: '" + sql + "'");
    }
    public PreparedStatementBase(XComponentContext context,
                                 String name,
                                 String[] services,
                                 DriverProvider provider,
                                 ConnectionBase xConnection,
                                 java.sql.Connection connection,
                                 String sql,
                                 Map<String, Property> properties,
                                 PropertyValue[] info)
    {
        super(context, name, services, provider, xConnection, properties, info);
        m_Connection = connection;
        m_Sql = sql;
    }


    protected java.sql.PreparedStatement _getStatement()
        throws SQLException
    {
        if (m_Statement == null)
        {
            m_Statement = m_Connection.prepareStatement(m_Sql, m_ResultSetType, m_ResultSetConcurrency, m_AutoGeneratedKeys);
            _setStatement(m_Statement);
        }
        return m_Statement;
    }


    protected java.sql.PreparedStatement _getWrapper()
    {
        return m_Statement;
    }


}
