/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020 https://prrvchr.github.io                                     ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
*/
package io.github.prrvchr.uno.sdbc;

import com.sun.star.beans.PropertyVetoException;
import com.sun.star.lang.WrappedTargetException;
import com.sun.star.lang.XServiceInfo;
import com.sun.star.logging.LogLevel;
import com.sun.star.sdbc.SQLException;
import com.sun.star.sdbc.XCloseable;
import com.sun.star.sdbc.XGeneratedResultSet;
import com.sun.star.sdbc.XMultipleResults;
import com.sun.star.sdbc.XResultSet;
import com.sun.star.sdbc.XStatement;
import com.sun.star.sdbc.XWarningsSupplier;
import com.sun.star.uno.Any;
import com.sun.star.uno.Type;
import com.sun.star.util.XCancellable;

import io.github.prrvchr.uno.beans.PropertySet;
import io.github.prrvchr.uno.beans.PropertySetAdapter.PropertyGetter;
import io.github.prrvchr.uno.beans.PropertySetAdapter.PropertySetter;
import io.github.prrvchr.uno.helper.PropertyIds;
import io.github.prrvchr.uno.helper.Resources;
import io.github.prrvchr.uno.helper.UnoHelper;
import io.github.prrvchr.uno.lang.ServiceInfo;
import io.github.prrvchr.uno.sdbc.ConnectionLog.ObjectType;


public abstract class StatementMain
    extends PropertySet
    implements XServiceInfo,
               XWarningsSupplier,
               XCancellable,
               XCloseable,
               XGeneratedResultSet,
               XMultipleResults
{

    private final String m_service;
    private final String[] m_services;
    protected ConnectionBase m_Connection;
    protected final ConnectionLog m_logger;
    protected java.sql.Statement m_Statement = null;
    protected XStatement m_GeneratedStatement;
    protected String m_Sql;

    private String m_CursorName = "";
    private int m_FetchDirection = java.sql.ResultSet.FETCH_FORWARD;
    private int m_FetchSize = 0;
    private int m_MaxFieldSize = 0;
    private int m_MaxRows = 0;
    private int m_QueryTimeout = 0;
    // FIXME: We are doing lazy loading on Statement because we need this property to create one!!!
    protected int m_ResultSetConcurrency = java.sql.ResultSet.CONCUR_READ_ONLY;
    // FIXME: We are doing lazy loading on Statement because we need this property to create one!!!
    protected int m_ResultSetType = java.sql.ResultSet.TYPE_FORWARD_ONLY;
    protected int m_AutoGeneratedKeys = java.sql.Statement.RETURN_GENERATED_KEYS;


    // The constructor method:
    public StatementMain(String service,
                         String[] services,
                         ConnectionBase connection)
    {
        m_service = service;
        m_services = services;
        m_Connection = connection;
        m_logger = new ConnectionLog(connection.getLogger(), ObjectType.STATEMENT);
        registerProperties();
    }

    public int getObjectId()
    {
        return m_logger.getObjectId();
    }

    private void registerProperties() {
        registerProperty(PropertyIds.CURSORNAME.name, PropertyIds.CURSORNAME.id, Type.STRING,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getCursorName();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setCursorName((String)value);
                }
            });
        registerProperty(PropertyIds.RESULTSETCONCURRENCY.name, PropertyIds.RESULTSETCONCURRENCY.id, Type.LONG,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getResultSetConcurrency();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setResultSetConcurrency((int)value);
                }
            });
        registerProperty(PropertyIds.RESULTSETTYPE.name, PropertyIds.RESULTSETTYPE.id, Type.LONG,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getResultSetType();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setResultSetType((int)value);
                }
            });
        registerProperty(PropertyIds.FETCHDIRECTION.name, PropertyIds.FETCHDIRECTION.id, Type.LONG,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getFetchDirection();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setFetchDirection((int)value);
                }
            });
        registerProperty(PropertyIds.FETCHSIZE.name, PropertyIds.FETCHSIZE.id, Type.LONG,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getFetchSize();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setFetchSize((int)value);
                }
            });
        registerProperty(PropertyIds.MAXFIELDSIZE.name, PropertyIds.MAXFIELDSIZE.id, Type.LONG,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getMaxFieldSize();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setMaxFieldSize((int)value);
                }
            });
        registerProperty(PropertyIds.MAXROWS.name, PropertyIds.MAXROWS.id, Type.LONG,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getMaxRows();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setMaxRows((int)value);
                }
            });
        registerProperty(PropertyIds.QUERYTIMEOUT.name, PropertyIds.QUERYTIMEOUT.id, Type.LONG,
            new PropertyGetter() {
                @Override
                public Object getValue() throws WrappedTargetException {
                    return _getQueryTimeout();
                }
            },
            new PropertySetter() {
                @Override
                public void setValue(Object value) throws PropertyVetoException, IllegalArgumentException, WrappedTargetException {
                    _setQueryTimeout((int)value);
                }
            });
    }

    protected abstract void _createStatement() throws SQLException;
    protected abstract XResultSet _getResultSet(java.sql.ResultSet resultset) throws SQLException;


    protected void _setStatement()
        throws java.sql.SQLException
    {
        if (m_CursorName != "") {
            m_Statement.setCursorName(m_CursorName);
        }
        m_Statement.setFetchDirection(m_FetchDirection);
        m_Statement.setFetchSize(m_FetchSize);
        m_Statement.setMaxFieldSize(m_MaxFieldSize);
        m_Statement.setMaxRows(m_MaxRows);
        m_Statement.setQueryTimeout(m_QueryTimeout);
        
    }


    private synchronized void _setCursorName(String cursor)
        throws WrappedTargetException
    {
        System.out.println("StatementMain._setCursorName() Value: " + cursor);
        m_CursorName = cursor;
        if (m_Statement != null) {
            try {
                m_Statement.setCursorName(cursor);
            }
            catch (java.sql.SQLException e) {
                throw new WrappedTargetException("SQL error", this, UnoHelper.getSQLException(e, this));
            }
        }
    }

    private String _getCursorName()
    {
        return m_CursorName;
    }

    private synchronized void _setFetchDirection(int value)
        throws WrappedTargetException
    {
        m_FetchDirection = value;
        if (m_Statement != null) {
            try {
                m_Statement.setFetchDirection(value);
            }
            catch (java.sql.SQLException e) {
                throw new WrappedTargetException("SQL error", this, UnoHelper.getSQLException(e, this));
            }
        }
    }
    private int _getFetchDirection()
    {
        return m_FetchDirection;
    }

    private synchronized void _setFetchSize(int value)
        throws WrappedTargetException
    {
        m_FetchSize = value;
        if (m_Statement != null) {
            try {
                m_Statement.setFetchSize(value);
            }
            catch (java.sql.SQLException e) {
                throw new WrappedTargetException("SQL error", this, UnoHelper.getSQLException(e, this));
            }
        }
    }
    private int _getFetchSize()
    {
        return m_FetchSize;
    }

    private synchronized void _setMaxFieldSize(int value)
        throws WrappedTargetException
    {
        m_MaxFieldSize = value;
        if (m_Statement != null) {
            try {
                m_Statement.setMaxFieldSize(value);
            }
            catch (java.sql.SQLException e) {
                throw new WrappedTargetException("SQL error", this, UnoHelper.getSQLException(e, this));
            }
        }
    }
    private int _getMaxFieldSize()
    {
        return m_MaxFieldSize;
    }

    private synchronized void _setMaxRows(int value)
        throws WrappedTargetException
    {
        m_MaxRows = value;
        if (m_Statement != null) {
            try {
                m_Statement.setMaxRows(value);
            }
            catch (java.sql.SQLException e) {
                throw new WrappedTargetException("SQL error", this, UnoHelper.getSQLException(e, this));
            }
        }
    }
    private int _getMaxRows()
    {
        return m_MaxRows;
    }

    private synchronized void _setQueryTimeout(int value)
        throws WrappedTargetException
    {
        m_QueryTimeout = value;
        if (m_Statement != null) {
            try {
                m_Statement.setQueryTimeout(value);
            }
            catch (java.sql.SQLException e) {
                throw new WrappedTargetException("SQL error", this, UnoHelper.getSQLException(e, this));
            }
        }
    }
    private int _getQueryTimeout()
    {
        return m_QueryTimeout;
    }

    private synchronized void _setResultSetConcurrency(int value)
    {
        // FIXME: We are doing lazy loading on Statement because we need this property to create one!!!
        m_logger.log(LogLevel.FINE, Resources.STR_LOG_RESULT_SET_CONCURRENCY, value);
        m_ResultSetConcurrency = value;
        if (m_Statement != null) {
            try {
                m_Statement.close();
            }
            catch (java.sql.SQLException e) {
                UnoHelper.getSQLException(e, this);
            }
            finally {
                m_Statement = null;
            }
        }
    }
    private int _getResultSetConcurrency()
    {
        if (m_Statement != null) {
            try {
                return m_Statement.getResultSetConcurrency();
            }
            catch (java.sql.SQLException e) {
                UnoHelper.getSQLException(e, this);
            }
        }
        return m_ResultSetConcurrency;
    }

    private synchronized void _setResultSetType(int value)
    {
        // FIXME: We are doing lazy loading on Statement because we need this property to create one!!!
        m_logger.log(LogLevel.FINE, Resources.STR_LOG_RESULT_SET_TYPE, value);
        m_ResultSetType = value;
        if (m_Statement != null) {
            try {
                m_Statement.close();
            }
            catch (java.sql.SQLException e) {
                UnoHelper.getSQLException(e, this);
            }
            finally {
                m_Statement = null;
            }
        }
    }
    private int _getResultSetType()
    {
        if (m_Statement != null) {
            try {
                return m_Statement.getResultSetType();
            }
            catch (java.sql.SQLException e) {
                UnoHelper.getSQLException(e, this);
            }
        }
        return m_ResultSetType;
    }


    // com.sun.star.lang.XServiceInfo:
    @Override
    public String getImplementationName()
    {
        return ServiceInfo.getImplementationName(m_service);
    }

    @Override
    public String[] getSupportedServiceNames()
    {
        return ServiceInfo.getSupportedServiceNames(m_services);
    }

    @Override
    public boolean supportsService(String service)
    {
        return ServiceInfo.supportsService(m_services, service);
    }


    // com.sun.star.sdbc.XWarningsSupplier:
    @Override
    public void clearWarnings() throws SQLException
    {
        if (m_Connection.getProvider().supportWarningsSupplier())
            WarningsSupplier.clearWarnings(m_Statement, this);
    }


    @Override
    public Object getWarnings() throws SQLException
    {
        if (m_Connection.getProvider().supportWarningsSupplier())
            return WarningsSupplier.getWarnings(m_Statement, this);
         return Any.VOID;
    }


    // com.sun.star.lang.XComponent
    @Override
    protected synchronized void postDisposing() {
        super.postDisposing();
        m_logger.log(LogLevel.FINE, Resources.STR_LOG_CLOSING_STATEMENT);
        if (m_Statement != null) {
            try {
                m_Statement.close();
            }
            catch (java.sql.SQLException e) {
                m_logger.logp(LogLevel.WARNING, e);
            }
            m_Statement = null;
        }
        UnoHelper.disposeComponent(m_GeneratedStatement);
    }

    // com.sun.star.sdbc.XCloseable
    @Override
    public void close() throws SQLException
    {
        System.out.println("StatementMain.close() **************************************");
        checkDisposed();
        dispose();
    }


    // com.sun.star.util.XCancellable:
    @Override
    public void cancel()
    {
        try {
            _createStatement();
            m_Statement.cancel();
        }
        catch (SQLException | java.sql.SQLException e) {
            System.out.println("StatementMain.cancel() ERROR");
        }
    }


    // com.sun.star.sdbc.XGeneratedResultSet:
    @Override
    public XResultSet getGeneratedValues()
            throws SQLException
    {
        _createStatement();
        XResultSet result = null;
        try {
            result = _getResultSet(m_Statement.getGeneratedKeys());
        }
        catch (java.sql.SQLException e) {
            throw UnoHelper.getSQLException(e, this);
        }
        if (result == null) {
            if (m_Connection.getProvider().isAutoRetrievingEnabled()) {
                String statement = m_Connection.getProvider().getTransformedGeneratedStatement(m_Sql);
                if (!statement.isEmpty()) {
                    UnoHelper.disposeComponent(m_GeneratedStatement);
                    m_GeneratedStatement = m_Connection.createStatement();
                    result = m_GeneratedStatement.executeQuery(statement);
                }
            }
        }
        return result;
    }


    // com.sun.star.sdbc.XMultipleResults:
    @Override
    public boolean getMoreResults() throws SQLException
    {
        try {
            _createStatement();
            return m_Statement.getMoreResults();
        }
        catch (java.sql.SQLException e) {
            throw UnoHelper.getSQLException(e, this);
        }
    }

    @Override
    public XResultSet getResultSet() throws SQLException
    {
        try {
            _createStatement();
            return _getResultSet(m_Statement.getResultSet());
        }
        catch (java.sql.SQLException e) {
            throw UnoHelper.getSQLException(e, this);
        }
    }

    @Override
    public int getUpdateCount() throws SQLException
    {
        try {
            _createStatement();
            return m_Statement.getUpdateCount();
        }
        catch (java.sql.SQLException e) {
            throw UnoHelper.getSQLException(e, this);
        }
    }


}
